export const TRANSACTIONS_LOADING = "TRANSACTIONS_LOADING";
export const TRANSACTIONS_ERROR = "TRANSACTIONS_ERROR";
export const TRANSACTIONS_SET = "TRANSACTIONS_SET";
export const CHANGE_FILE = "CHANGE_FILE";
export const SUBMIT = "SUBMIT";
