
version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file: .env
  web:
      build:
        context: .
        dockerfile: Dockerfile
      command: bundle exec rails s -p 3000 -b '0.0.0.0'
      container_name: cnab_app
      volumes:
          - .:/cnab
      ports:
          - "3000:3000"
      depends_on:
          - db
      env_file: .env
