version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=desafio_dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "python desafio_dev/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
