version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: TransacionsDB
    ports:
      - "3306:3306"

  springboot-app:
    build:
      context: ./desafio-dev
    ports:
      - "8080:8080"
    depends_on:
      - mysql
