version: "3.3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    command: mysqld --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: password

  app:
    build: .
    tty: true
    container_name: finance-report
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/finance-report
    ports:
      - "3000:3000"
    depends_on:
      - mysql
