version: '3.4'
services:
  db:
    image: postgres
    container_name: desafio-dev-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
volumes:
  db: