# Generated by Django 3.1 on 2021-09-06 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTransacao',
            fields=[
                ('tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=22)),
                ('natureza', models.CharField(max_length=7)),
                ('sinal', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cnab',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_ocorrencia', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cpf', models.IntegerField(blank=True, null=True)),
                ('cartao', models.CharField(blank=True, max_length=12, null=True)),
                ('hora', models.TimeField()),
                ('dono_loja', models.CharField(blank=True, max_length=14, null=True)),
                ('nome_loja', models.CharField(blank=True, max_length=19, null=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipotransacao')),
            ],
        ),
    ]
