# Generated by Django 3.2.7 on 2021-09-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnab',
            name='cpf',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='cnab',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
