spring:
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    enabled: false
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/FINANCIAL_TRANSACTIONS
    username: ft_user
    password: ft_pwd