"""Creating cnab model and user

Revision ID: 61352d344a3c
Revises: 
Create Date: 2022-04-16 14:16:46.953964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61352d344a3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Integer(), nullable=False),
    sa.Column('occurrence_at', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('card', sa.String(length=12), nullable=False),
    sa.Column('store_owner', sa.String(length=14), nullable=False),
    sa.Column('store_name', sa.String(length=19), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('cnabs')
    # ### end Alembic commands ###
