"""stores

Revision ID: 695a74afbced
Revises: 61352d344a3c
Create Date: 2022-04-17 01:37:33.290446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695a74afbced'
down_revision = '61352d344a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=19), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cnabs', sa.Column('store_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_cnabs_store_id'), 'cnabs', ['store_id'], unique=False)
    op.create_foreign_key(None, 'cnabs', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cnabs', type_='foreignkey')
    op.drop_index(op.f('ix_cnabs_store_id'), table_name='cnabs')
    op.drop_column('cnabs', 'store_id')
    op.drop_table('stores')
    # ### end Alembic commands ###
