spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    platform: h2
    initialization-mode: always
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true