#state 1
FROM node:14.16.1 AS node-front

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm i --legacy-peer-deps 

COPY . . 

RUN npm run build --prod

#state 2
FROM nginx
COPY --from=node-front / /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80