
server:
    port: 8080
    servlet:
        context-path: /movimentacao-api

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
        
    jpa:
        database: POSTGRESQL
        show-sql: false
        properties:
            hibernate:
                default_schema: public
    liquibase:
        enabled: true
        change-log: classpath:db/master.xml
        default-schema: public

springdoc:
    swagger-ui:
        path: /doc