USE FINANCIAL_TRANSACTIONS;

CREATE TABLE IF NOT EXISTS STORES (
    ID_STORE INT NOT NULL AUTO_INCREMENT,
    NAM_STORE VARCHAR(19) UNIQUE,
    PRIMARY KEY (ID_STORE)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS OWNERS (
    ID_OWNER INT NOT NULL AUTO_INCREMENT,
    NAM_OWNER VARCHAR(14) UNIQUE,
    PRIMARY KEY (ID_OWNER)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS DOCUMENTS (
    ID_DOCUMENT INT NOT NULL AUTO_INCREMENT,
    NUM_DOCUMENT VARCHAR(11) NOT NULL UNIQUE,
    PRIMARY KEY (ID_DOCUMENT)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID_TRANSACTION INT NOT NULL AUTO_INCREMENT,
    COD_TRANSACTION_TYPE INT NOT NULL,
    NUM_CARD VARCHAR(12) NOT NULL,
    ID_STORE INT NOT NULL,
    ID_OWNER INT NOT NULL,
    ID_DOCUMENT INT NOT NULL,
    NUM_AMOUNT FLOAT,
    DATE_OCCURRENCE DATE NOT NULL,
    DATE_CREATION DATE NOT NULL,
    PRIMARY KEY (ID_TRANSACTION)
) ENGINE=INNODB;
