CREATE TABLE IF NOT EXISTS STORES (
    ID_STORE INT NOT NULL AUTO_INCREMENT,
    NAM_STORE VARCHAR(19),
    PRIMARY KEY (ID_STORE)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS OWNERS (
    ID_OWNER INT NOT NULL AUTO_INCREMENT,
    NAM_OWNER VARCHAR(14),
    PRIMARY KEY (ID_OWNER)
)ENGINE=INNODB;;

CREATE TABLE IF NOT EXISTS RECIPIENT_DOCUMENTS (
    ID_RECIPIENT_DOCUMENT INT NOT NULL AUTO_INCREMENT,
    NUM_DOCUMENT INT NOT NULL,
    PRIMARY KEY (ID_RECIPIENT_DOCUMENT)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS TRANSACTION_TYPES (
    ID_TRANSACTION_TYPE INT NOT NULL AUTO_INCREMENT,
    DESC_TRANSACTION VARCHAR(25) NOT NULL,
    TYPE VARCHAR(3) NOT NULL,
    PRIMARY KEY (ID_TRANSACTION_TYPE)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID_TRANSACTION INT NOT NULL AUTO_INCREMENT,
    ID_TRANSACTION_TYPE INT NOT NULL,
    ID_STORE INT NOT NULL,
    ID_OWNER INT NOT NULL,
    ID_RECIPIENT_DOCUMENT INT NOT NULL,
    NUM_AMOUNT FLOAT,
    DATE_OCCURRENCE DATE NOT NULL,
    DATE_CREATION DATE NOT NULL,
    PRIMARY KEY (ID_TRANSACTION),
    FOREIGN KEY (ID_STORE) REFERENCES STORES(ID_STORE),
    FOREIGN KEY (ID_OWNER) REFERENCES OWNERS(ID_OWNER),
    FOREIGN KEY (ID_TRANSACTION_TYPE) REFERENCES TRANSACTION_TYPES(ID_TRANSACTION_TYPE),
    FOREIGN KEY (ID_RECIPIENT_DOCUMENT) REFERENCES RECIPIENT_DOCUMENTS(ID_RECIPIENT_DOCUMENT)
) ENGINE=INNODB;

GRANT SELECT, UPDATE, INSERT, DELETE ON FINANCIAL_TRANSACTIONS.* TO 'ft_user'@'%';
GRANT ALL ON FINANCIAL_TRANSACTIONS.* TO 'migration_user'@'%';