ALTER TABLE STORES ADD COLUMN ID_TRANSACTION INT;
ALTER TABLE OWNERS ADD COLUMN ID_TRANSACTION INT;
ALTER TABLE DOCUMENTS ADD COLUMN ID_TRANSACTION INT;

ALTER TABLE STORES ADD FOREIGN KEY (ID_TRANSACTION) REFERENCES TRANSACTIONS(ID_TRANSACTION);
ALTER TABLE OWNERS ADD FOREIGN KEY (ID_TRANSACTION) REFERENCES TRANSACTIONS(ID_TRANSACTION);
ALTER TABLE DOCUMENTS ADD FOREIGN KEY (ID_TRANSACTION) REFERENCES TRANSACTIONS(ID_TRANSACTION);

ALTER TABLE TRANSACTIONS ADD FOREIGN KEY (ID_STORE) REFERENCES STORES(ID_STORE);
ALTER TABLE TRANSACTIONS ADD FOREIGN KEY (ID_OWNER) REFERENCES OWNERS(ID_OWNER);
ALTER TABLE TRANSACTIONS ADD FOREIGN KEY (ID_DOCUMENT) REFERENCES DOCUMENTS(ID_DOCUMENT);
