ALTER TABLE TRANSACTIONS ADD FOREIGN KEY (ID_STORE) REFERENCES STORES(ID_STORE);
ALTER TABLE TRANSACTIONS ADD FOREIGN KEY (ID_OWNER) REFERENCES OWNERS(ID_OWNER);
ALTER TABLE TRANSACTIONS ADD FOREIGN KEY (ID_DOCUMENT) REFERENCES DOCUMENTS(ID_DOCUMENT);
