name: Build and Publish Docker image

on:
  workflow_call:
    secrets:
      VERSION:
        required: true
      PROJECT_ID:
        required: true
      CLOUD_CREDENTIAL:
        required: true
      ZONE:
        required: true
      CLUSTER_NAME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          service_account_key: ${{ secrets.CLOUD_CREDENTIAL }}
          project_id: ${{ secrets.PROJECT_ID }}
      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          location: ${{ secrets.ZONE }}
          project_id: ${{ secrets.PROJECT_ID }}
      - run: kubectl apply -f .\kube\
      - run: kubectl rollout status deployment/desafio-dev
      - run: kubectl get services -o wide

