# Generated by Django 4.0.4 on 2022-05-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cnabModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transacao', models.IntegerField()),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cpf', models.CharField(max_length=11)),
                ('cartao', models.CharField(max_length=16)),
                ('hora_transacao', models.TimeField()),
                ('nome_dono_loja', models.CharField(max_length=50)),
                ('nome_loja', models.CharField(max_length=50)),
            ],
        ),
    ]
